version: '3'

services:
  database:
    container_name: mysql_db

    image: mysql
    environment:
      MYSQL_DATABASE: DockerTest
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_HOST: 'root'

    ports:
      - "3306:3306"
    networks:
      - test_network

  application:
    container_name: docker_app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/DockerTest
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - database
    networks:
      - test_network
networks:
  test_network: